// @ts-check
/**
 * cv-writers.mjs — the alternatives to "let a 7B rewrite every bullet".
 *
 * Phase 3 has always had exactly one writer: hand `snipe-cv` the selected CV and
 * ask for tailored JSON. Everything downstream of that call — eighteen guard
 * functions in local-pdf-offer.mjs — exists to undo what it breaks. Two of those
 * guards are the evidence that motivated this file: `verifyBulletFigures` reverts
 * a rewrite to its CV source whenever a figure was dropped, and doing so *raised*
 * ats_coverage (+0.025, 16 wins 1 loss) and grounding (+0.105). The source bullet
 * carried more of the posting's own vocabulary than the rewrite of it did.
 *
 * If reverting helps when a figure is lost, the obvious question is whether it
 * helps when one isn't. `verbatim` answers that: the same selection, rendered
 * with no generation call at all.
 *
 * Self-check: node batch/cv-writers.mjs
 */

import { parseCvSections, parseEntries, entryCompany, padProjectDescriptions } from './cv-select.mjs';

const STOPWORDS = new Set(['and','the','of','for','to','in','with','on','our','you','your','we','is','are','as','at','an','or','by','be','this','that','will','have','has','from','using','use']);

/**
 * The `.` in the character class is there for `Next.js` and `node.js`, but it also
 * welds a sentence-final period onto the last word — a JD ending "…we need JWT."
 * yields `jwt.`, which matches the CV's `jwt` nowhere. Trim the edges after the
 * match so the dot only survives where it is medial.
 * @param {string} s
 */
function tokenize(s) {
  return (String(s || '').toLowerCase().match(/[a-z0-9+#.]{3,}/g) || [])
    .map(w => w.replace(/^\.+|\.+$/g, ''))
    .filter(w => w.length >= 3 && !STOPWORDS.has(w));
}

/**
 * The CV's `**Category:** a, b, c` skill lines, as `{category, items[]}`.
 *
 * Parenthesised asides are dropped before the split, not after: several items
 * carry a comma inside them ("Kubernetes (working knowledge, self-study …)") and
 * splitting first ships "Kubernetes (Working Knowledge" as a skill.
 * @param {string} cvText
 */
export function parseSkillCategories(cvText) {
  const sec = (cvText || '').split(/^##\s+/m).find(s => /^Skills/i.test(s)) || '';
  return [...sec.matchAll(/^\*\*([^*]+):\*\*\s*(.+)$/gm)].map(m => ({
    category: m[1].trim(),
    items: m[2].replace(/\([^)]*\)/g, '').split(',').map(s => s.trim()).filter(Boolean),
  }));
}

/**
 * Skill categories ranked by JD overlap, items within each ranked the same way.
 *
 * Deterministic and grounded by construction — every item is lifted verbatim from
 * cv.md — which is the whole point: `filterSkillItems` exists downstream purely to
 * throw away the ones the model invented, and it has nothing to do here.
 *
 * @param {string} cvText
 * @param {string} jdText
 * @param {number} maxCats
 * @param {number} maxItems
 * @returns {{category: string, items: string}[]}
 */
export function selectSkills(cvText, jdText, maxCats = 6, maxItems = 12) {
  const jd = new Set(tokenize(jdText));
  const hits = (s) => tokenize(s).filter(t => jd.has(t)).length;
  return parseSkillCategories(cvText)
    .map((c, idx) => {
      const items = c.items
        .map((item, i) => ({ item, i, score: hits(item) }))
        .sort((a, b) => b.score - a.score || a.i - b.i)
        .slice(0, maxItems);
      // A category earns its slot on its items, not its name: "Security &
      // Cryptography" shares no token with a JD that asks for AES and OAuth.
      return { category: c.category, items, idx, score: items.reduce((a, b) => a + b.score, 0) };
    })
    .sort((a, b) => b.score - a.score || a.idx - b.idx)
    .slice(0, maxCats)
    // Back to CV order once the cut is made — the categories read as a list, and
    // reordering them by posting relevance makes the same CV look different to a
    // human reading two of them side by side for no gain.
    .sort((a, b) => a.idx - b.idx)
    .map(c => ({ category: c.category, items: c.items.map(x => x.item).join(', ') }));
}

/**
 * A tailored-CV content object built entirely from the selected CV, with no
 * generation call.
 *
 * `summary` is deliberately left null rather than filled: it is generated by its
 * own stage (summary-stage.mjs) and keeping that stage identical is what makes
 * this a clean test of the *bullet* rewrite rather than a test of two changes at
 * once. The caller fills it.
 *
 * `competencies` and `education_modules` are also left out — local-pdf-offer.mjs
 * already overwrites both with deterministic, JD-ranked selections regardless of
 * what the writer returned, so producing them here would be dead code.
 *
 * @param {string} selectedCv the CV that cv-select trimmed for this posting
 * @param {string} cvText the full cv.md
 * @param {string} jdText
 * @param {{projectBullets?: number}} [opts] 0 keeps the one-paragraph blurb
 * @returns {{summary: null, experience: any[], projects: any[], skills: any[]}}
 */
export function verbatimContent(selectedCv, cvText, jdText, opts = {}) {
  // 2, because that is what renders. Measured across four offers: two project
  // bullets fit the 2-page cap on all of them, three fit none. The density
  // ladder can trim further for a long-tail offer, but the default has to be a
  // shape that actually ships — the bench stops before the PDF, so a default
  // that only fits in principle would score well on every metric and produce a
  // three-page CV in production.
  const { projectBullets = 2 } = opts;
  const named = (n) => parseCvSections(selectedCv).find(s => s.name === n);
  const expSec = named('Experience');
  const projSec = named('Projects');

  const experience = expSec
    ? parseEntries(expSec.lines).entries.map(e => ({
        company: entryCompany(e),
        bullets: [...e.bullets],
      }))
    : [];

  // An empty description makes padProjectDescriptions build the whole blurb from
  // the project's own CV clauses, least-covered first — which is exactly the
  // verbatim rendering wanted here, and is already the shipped repair path for a
  // description the 7B truncated. Reusing it beats a second clause-joiner that
  // would drift from it.
  const projEntries = projSec ? parseEntries(projSec.lines).entries : [];
  const projects = padProjectDescriptions(
    projEntries.map(e => ({ name: e.head[0].replace(/^###\s+/, '').trim(), description: '' })),
    selectedCv)
    .map((p, i) => ({
      ...p,
      // Bullets alongside the blurb, not instead of it: the template picks the
      // list when it is there and falls back to the paragraph otherwise, so a
      // run with projectBullets 0 renders exactly as before.
      //
      // This is the field that carries the differentiators. cv-select already
      // ranked these bullets against the posting, and the paragraph form was
      // discarding all but the first clause or two of them — measured against
      // the Opus labels, every differentiator lost on a sampled offer was a
      // project bullet the blurb had no room for.
      bullets: projectBullets ? (projEntries[i]?.bullets || []).slice(0, projectBullets) : [],
    }));

  return { summary: null, experience, projects, skills: selectSkills(cvText, jdText) };
}

// ── self-check ────────────────────────────────────────────────────────────────

if (process.argv[1] && process.argv[1].endsWith('cv-writers.mjs')) {
  const assert = (await import('assert')).default;
  const cv = [
    '# X', '', '## Experience', '',
    '### Engineer', '**Acme** — London | Jan 2024 – Present', '',
    '- Shipped a thing serving 170 users', '- Cut latency by 80%', '',
    '## Projects', '', '### Widget', '**Personal** | Rust | 2025', '',
    '- Built a Rust widget with AES-256-GCM encryption and a lock-free ring buffer',
    '- Benchmarked it across 7 schemes and 5 payload sizes with bootstrap CIs', '',
    '## Skills', '',
    '**Languages:** Rust, Java, Python',
    '**Security:** AES-256-GCM, OAuth 2.0 (working knowledge, self-study), JWT',
    '**Cloud:** AWS, Docker',
  ].join('\n');

  const c = verbatimContent(cv, cv, 'We need Rust and AES-256-GCM encryption experience.');

  assert.equal(c.experience.length, 1, 'one employer');
  assert.deepEqual(c.experience[0].bullets,
    ['Shipped a thing serving 170 users', 'Cut latency by 80%'], 'bullets verbatim');
  assert.equal(c.projects.length, 1);
  assert.match(c.projects[0].description, /Rust widget/, 'description built from CV clauses');

  // The parenthesised aside must not split into a bogus item.
  const sec = parseSkillCategories(cv).find(s => s.category === 'Security');
  assert.deepEqual(sec.items, ['AES-256-GCM', 'OAuth 2.0', 'JWT'], 'aside stripped before split');

  // Security outranks Cloud on this JD, but CV order survives the cut.
  const cats = c.skills.map(s => s.category);
  assert.deepEqual(cats, ['Languages', 'Security', 'Cloud'], 'all three fit under maxCats');
  // Tight cut: Security is the only category this JD scores, so it must survive
  // it — and the pair must still come back in CV order, not relevance order.
  const two = selectSkills(cv, 'We need AES-256-GCM encryption.', 2);
  assert.deepEqual(two.map(s => s.category), ['Languages', 'Security'],
    'scored category kept, ties broken by CV order, output re-sorted by CV order');

  // Items inside a category are ranked, so a tight item cap keeps the matched one.
  const [oneItem] = selectSkills(cv, 'We need JWT.', 1, 1);
  assert.deepEqual(oneItem, { category: 'Security', items: 'JWT' }, 'items ranked within a category');

  console.log('cv-writers self-check OK');
}
