// @ts-check
/**
 * summary-stage.mjs — Phase 3 generation guards.
 *
 * Two jobs, both about making the generated prose true:
 *
 *   1. The summary is generated by its own call, fed the bullets that will
 *      actually appear on the CV. It used to be one field in a large JSON blob
 *      competing with five other sections, and its repair path
 *      (`reviseSummary`) was built from the JD and the profile narrative and
 *      **never saw the selected bullets at all** — structurally guaranteed to
 *      pull the summary toward the posting. That is the parroting failure mode,
 *      built into the repair.
 *
 *   2. A named product the CV never mentions is stripped, not counted. The
 *      two-tier vocabulary rule — capability phrases free, named products
 *      grounded — is aspirational until violations are actually rejected.
 */

import { parseCvSections, parseEntries, revertUnsupportedBullets,
         stripUnsupportedClauses } from './cv-select.mjs';

// ── Named-product vocabulary ──────────────────────────────────────────────────
/**
 * A closed vocabulary is deliberate. The alternative — treat any capitalised
 * unknown token as a product — flags every company name, role title and section
 * heading, and a guard that cries wolf gets switched off. This is a *detector*,
 * not a generator: a missing entry understates the count, it never invents one.
 *
 * Seeded from the 9 real violations found across 133 shipped CVs (gcp x3,
 * kotlin, golang, dbt, terraform, azure, angular) and extended to the products a
 * JD in this corpus is likely to name.
 */
export const NAMED_PRODUCTS = [
  // clouds & platforms
  'aws', 'azure', 'gcp', 'google cloud', 'heroku', 'digitalocean', 'cloudflare',
  'firebase', 'vercel', 'netlify', 'openshift', 'cloud foundry',
  // languages
  'kotlin', 'golang', 'scala', 'clojure', 'elixir', 'erlang', 'haskell', 'swift',
  'objective-c', 'perl', 'ruby', 'php', 'c#', 'f#', 'dart', 'julia', 'groovy',
  'visual basic', 'cobol', 'fortran', 'lua', 'r language',
  // frontend
  'angular', 'vue', 'svelte', 'ember', 'backbone', 'jquery', 'solidjs',
  'tailwind', 'bootstrap', 'material ui', 'sass', 'webpack', 'vite', 'nuxt',
  // backend & frameworks
  'django', 'flask', 'fastapi', 'rails', 'laravel', 'symfony', 'phoenix',
  'spring boot', 'quarkus', 'micronaut', 'nestjs', 'gin', 'echo framework',
  'asp.net', '.net core', 'entity framework',
  // data stores
  'cassandra', 'dynamodb', 'cockroachdb', 'couchbase', 'couchdb', 'neo4j',
  'influxdb', 'clickhouse', 'snowflake', 'bigquery', 'redshift', 'databricks',
  'oracle db', 'db2', 'mariadb', 'firestore', 'elasticsearch', 'opensearch',
  'timescaledb', 'scylladb', 'planetscale', 'supabase',
  // streaming & messaging
  'kafka', 'rabbitmq', 'pulsar', 'nats', 'activemq', 'sqs', 'kinesis',
  'flink', 'spark', 'hadoop', 'airflow', 'dagster', 'dbt', 'beam',
  // infra & ops
  'terraform', 'pulumi', 'ansible', 'puppet', 'chef', 'vagrant', 'nomad',
  'consul', 'vault', 'istio', 'linkerd', 'helm', 'argocd', 'flux',
  'cloudformation', 'packer', 'saltstack',
  // observability
  'datadog', 'new relic', 'splunk', 'sentry', 'grafana', 'jaeger', 'zipkin',
  'opentelemetry', 'pagerduty', 'dynatrace', 'appdynamics',
  // ci/cd & vcs
  'circleci', 'travis', 'teamcity', 'bamboo', 'gitlab ci', 'github actions',
  'bitbucket', 'azure devops', 'octopus deploy',
  // ml
  'pytorch', 'tensorflow', 'keras', 'jax', 'scikit-learn', 'huggingface',
  'langchain', 'llamaindex', 'mlflow', 'kubeflow', 'sagemaker', 'vertex ai',
  'weights & biases', 'ray',
  // saas / business
  'salesforce', 'sap', 'workday', 'servicenow', 'netsuite', 'hubspot',
  'shopify', 'magento', 'contentful', 'sanity', 'wordpress', 'drupal',
  'twilio', 'sendgrid', 'auth0', 'okta', 'keycloak', 'segment', 'snowplow',
  'looker', 'tableau', 'power bi', 'qlik', 'metabase', 'superset',
];

/** Normalised text with guaranteed leading/trailing space, for phrase matching. */
function phraseSpace(s) {
  return ` ${String(s || '').toLowerCase().replace(/[^a-z0-9+#.&-]+/g, ' ').replace(/\s+/g, ' ').trim()} `;
}
const hasPhrase = (haystack, phrase) => haystack.includes(` ${phrase} `);

/**
 * Credentials, institutions and affiliations that have to be grounded in `cv.md`.
 *
 * Same contract as NAMED_PRODUCTS: a *detector*, not a generator — a missing
 * entry understates the count, it never invents one. Seeded from a real
 * violation, where a summary called the candidate a "Russell Group graduate"
 * because the university has "Edinburgh" in its name; it is a post-1992
 * institution and the claim is simply false. A fabricated credential is worse
 * than a fabricated technology — it is checkable by anyone reading the CV, and
 * being caught inventing one ends the application.
 *
 * Entries a *truthful* CV states (this one does say "First Class Honours") are
 * listed too: the phrase is only flagged when `cv.md` lacks it, so listing it
 * costs nothing here and protects a CV that cannot claim it.
 */
export const NAMED_CREDENTIALS = [
  // institution tiers and affiliations
  'russell group', 'ivy league', 'oxbridge', 'red brick',
  // degree classes and honours
  'first class honours', 'upper second class', 'lower second class',
  'summa cum laude', 'magna cum laude', 'cum laude', 'valedictorian',
  'dean s list', 'with distinction',
  // degrees
  'phd', 'doctorate', 'mba', 'msc', 'meng', 'mphil', 'postgraduate',
  // professional certifications
  'cissp', 'cism', 'cisa', 'oscp', 'ceh', 'comptia', 'security+',
  'ccna', 'ccnp', 'rhce', 'pmp', 'prince2', 'itil', 'togaf',
  'aws certified', 'azure certified', 'google cloud certified',
  'certified kubernetes administrator', 'cka', 'ckad',
  'chartered engineer', 'chartered',
];

/**
 * Credentials the text claims that `cv.md` never mentions.
 * @param {string} text
 * @param {string} cvText
 * @returns {string[]}
 */
export function credentialFab(text, cvText) {
  const out = phraseSpace(text);
  const cv = phraseSpace(cvText);
  return NAMED_CREDENTIALS.filter(p => hasPhrase(out, p) && !hasPhrase(cv, p));
}

/**
 * Drop the clauses claiming a credential `cv.md` never mentions.
 *
 * Costs real content when a false credential shares a clause with a true one —
 * "Russell Group graduate with First Class Honours" loses the honours along with
 * the lie. That is the documented trade for products and it holds harder here:
 * shipping a shorter true summary beats shipping a longer false one.
 *
 * @param {string} text
 * @param {string} cvText
 * @returns {string}
 */
export function stripFabricatedCredentials(text, cvText) {
  return stripUnsupportedClauses(text, t => credentialFab(t, cvText).length > 0);
}

/**
 * Named products the text claims that `cv.md` never mentions.
 * @param {string} text
 * @param {string} cvText
 * @returns {string[]}
 */
export function productFab(text, cvText) {
  const out = phraseSpace(text);
  const cv = phraseSpace(cvText);
  return NAMED_PRODUCTS.filter(p => hasPhrase(out, p) && !hasPhrase(cv, p));
}

/**
 * Drop the clauses that name a product `cv.md` never mentions.
 *
 * Sentence-level, then comma-clause-level: "Built services in Rust, Kotlin and
 * Go" should lose Kotlin, not the whole sentence. Falls back to deleting the
 * sentence only when the clause surgery cannot clear it, because shipping a
 * shorter true summary beats shipping a longer false one.
 *
 * @param {string} text
 * @param {string} cvText
 * @returns {string}
 */
export function stripFabricatedProducts(text, cvText) {
  return stripUnsupportedClauses(text, t => productFab(t, cvText).length > 0);
}

/**
 * Revert every experience bullet naming a product `cv.md` never mentions.
 *
 * Bullets get reverted rather than clause-stripped because each one has a known
 * source line in `cv.md` — the untailored truth is right there, and it fills the
 * slot. Summaries and project blurbs have no single source line, so those get
 * `stripFabricatedProducts` instead.
 *
 * @param {any[]} items
 * @param {string} cvText
 */
export function verifyBulletProducts(items, cvText) {
  return revertUnsupportedBullets(items, cvText, b => productFab(b, cvText).length > 0);
}

/**
 * Drop skill items naming a product `cv.md` never mentions.
 *
 * The skills array is model-written, unlike `competencies` and
 * `education_modules` which are code-derived from `cv.md` and so cannot
 * fabricate. It was the one generated surface T2 initially missed, and it was
 * the single surviving `product_fab` on the benchmark: a Flock posting asking
 * for AWS Lambda/SQS/EventBridge produced the skill row
 * "AWS (Lambda, SQS, EventBridge), Spring Boot, RabbitMQ, PostgreSQL" against a
 * CV that names AWS but never SQS.
 *
 * Item-level, because a skills row is already a comma-separated list — dropping
 * the offending item is the natural repair and keeps the true ones. A row left
 * empty is removed rather than shipped as a bare heading. Parenthesised asides
 * are pruned in place, so "AWS (Lambda, SQS)" becomes "AWS (Lambda)".
 *
 * @param {any[]} skills
 * @param {string} cvText
 */
export function filterSkillItems(skills, cvText) {
  if (!Array.isArray(skills)) return skills;
  const clean = (item) => {
    // Prune inside the parentheses first, so one bad sub-item does not cost the
    // whole entry ("AWS (Lambda, SQS)" must not lose AWS).
    const withAside = item.replace(/\(([^)]*)\)/g, (whole, inner) => {
      const kept = inner.split(',').map(x => x.trim())
        .filter(x => x && !productFab(x, cvText).length);
      return kept.length ? `(${kept.join(', ')})` : '';
    }).replace(/\s+/g, ' ').trim();
    return productFab(withAside, cvText).length ? '' : withAside;
  };
  return skills
    .map(s => {
      const items = String(s?.items || '').split(',').map(x => clean(x.trim())).filter(Boolean);
      return { ...s, items: items.join(', ') };
    })
    .filter(s => s.items);
}

// ── Summary stage ─────────────────────────────────────────────────────────────

/**
 * The bullets that will actually appear on this CV, in CV order.
 * This is the evidence the summary must describe — not the JD, and not the
 * whole of `cv.md`, but the specific subset `cv-select` chose for this offer.
 * @param {string} selectedCv the post-selection CV handed to the tailor model
 * @returns {string[]}
 */
export function selectedBullets(selectedCv) {
  const out = [];
  try {
    for (const sec of parseCvSections(selectedCv)) {
      if (sec.name !== 'Experience' && sec.name !== 'Projects') continue;
      for (const e of parseEntries(sec.lines).entries) {
        const name = e.head[0].replace(/^###\s+/, '').trim();
        for (const b of e.bullets) out.push(`${name}: ${b}`);
      }
    }
  } catch { /* odd CV shape — caller falls back */ }
  return out;
}

/**
 * The template is the industry-standard one, not an invention. Every current CV
 * guide converges on the same three moves — positioning, the skills the posting
 * named, one quantified achievement — in 2-4 sentences and 50-80 words, with the
 * employer's own wording for the skills the candidate genuinely has, because a
 * keyword search and a 7-second human scan both read for exactly that.
 *
 * The previous prompt withheld the posting entirely, because handing a 7B the
 * JD's vocabulary produced straight parroting ("expertise in networking, HFT and
 * financial markets" against a CV showing none of it). That defence cost the
 * summary its reason to exist: with no posting in view the model wrote whichever
 * bullets it liked, and the shipped shape was three achievements with the bullet
 * points removed — no positioning clause, redundant with the Experience section
 * directly below it, and on offer 305 it spent 2 of its 3 sentences on a Java
 * coursework project for a TypeScript/Node/AWS posting.
 *
 * So the requirements come back and the model is the 30B rather than the 7B. The
 * anti-parroting rule is now explicit and one-directional: **the posting supplies
 * the wording, the evidence supplies the facts**, and a requirement the evidence
 * cannot answer is not mentioned at all. That is the honest form of keyword
 * matching — it puts the recruiter's term on the page only where the candidate
 * really has the thing. The grounding guards are unchanged and still run after
 * this call, so a term the model borrows and `cv.md` cannot support is removed
 * rather than trusted.
 */
const SUMMARY_SYSTEM = [
  'You write ONE professional summary for a CV. Output ONLY the summary as plain text —',
  'no JSON, no quotes, no preamble, no label.',
  '',
  'Shape — exactly three sentences, in this order:',
  '  1. POSITIONING. What the candidate IS: the posting\'s own job title, plus the one',
  '     specialisation the evidence most supports. Never open this sentence with a verb.',
  '  2. SKILLS. The two or three requirements from the posting that the evidence',
  '     actually answers, in the posting\'s wording.',
  '  3. PROOF. One concrete achievement from the evidence, with its figure.',
  '',
  'Rules:',
  '- Length: 50 to 70 words in total. Count them.',
  '- Implied first person: never use a name, never "he"/"she"/"they".',
  '- The posting supplies the WORDING. The evidence supplies the FACTS. Use a',
  '  requirement\'s exact term only where a specific line of the evidence shows that',
  '  work. A requirement the evidence cannot answer is left out entirely — never',
  '  claim it, never hedge it.',
  '- Do not state a number of years of experience, and do not label a seniority',
  '  level. The evidence contains neither.',
  '- Use ONE job title. Never invent a hybrid or dual title.',
  '- Never name the target company, and never claim to have worked for them.',
  '- BE SPECIFIC. Name the actual systems, technologies and figures that appear',
  '  in the evidence. A summary that could describe any engineer is a failed',
  '  summary. Never write "proven track record", "high-impact", "diverse',
  '  domains", "innovative solutions", "cutting-edge" or "passionate about".',
].join('\n');

/**
 * Posting first, evidence second, so the instruction to take every fact from the
 * evidence sits next to the evidence itself.
 *
 * The requirements are capped because Block B runs to a dozen on some reports and
 * the tail is the part a posting cares least about — the same cap `goldset.mjs`
 * uses when it shows requirements to a human.
 *
 * @param {string[]} bullets the selected CV bullets — the ONLY source of fact
 * @param {string} role
 * @param {string[]} reqs Block B requirements, in the posting's own wording
 */
export function summaryUser(bullets, role, reqs = []) {
  const ev = bullets.length ? bullets.map(b => `- ${b}`).join('\n') : '(none)';
  const req = reqs.length
    ? reqs.slice(0, 8).map(r => `- ${r}`).join('\n')
    : '(none listed — describe the evidence)';
  return [
    '## What the posting asks for — use this WORDING, never as a claim',
    '',
    req,
    '',
    '## Evidence — the bullets that will appear on this CV. The only source of fact.',
    '',
    ev,
    '',
    `## Target role title: ${role || 'software engineering'}`,
    '',
    'Write the three-sentence, 50-70 word summary now.',
  ].join('\n');
}

// ── Code-side candidate scoring ───────────────────────────────────────────────

const CONTENT = /[a-z0-9+#.]{3,}/g;
const contentToks = (s) => new Set((String(s || '').toLowerCase().match(CONTENT) || []));

/**
 * Fraction of the summary's content words that actually appear in the evidence.
 *
 * This is the direct measure of parroting: a summary lifted from the posting
 * scores low here even when it reads well, because the posting's vocabulary is
 * not the CV's. It is the term that stops `summary_jd_fit` being gamed.
 */
export function evidenceOverlap(text, bullets) {
  const t = contentToks(text);
  if (!t.size) return 0;
  const ev = contentToks(bullets.join(' '));
  let n = 0;
  for (const w of t) if (ev.has(w)) n++;
  return n / t.size;
}

// Function words are what separate prose from a keyword dump. Prose runs
// 0.20-0.40 of its tokens here; a slash-separated tag list runs near zero.
const FUNCTION_WORDS = new Set([
  'the', 'and', 'a', 'an', 'of', 'in', 'to', 'for', 'with', 'on', 'at', 'by',
  'from', 'as', 'that', 'this', 'it', 'its', 'into', 'over', 'across', 'where',
  'which', 'while', 'their', 'has', 'have', 'was', 'were', 'been', 'is', 'are',
]);

/**
 * Is this prose at all?
 *
 * Rewarding evidence overlap creates an obvious exploit: a dense list of CV
 * keywords maximises overlap while being unreadable. The stage produced exactly
 * that — "Senior Software Engineer (Graduate) / Production-Grade Backend Systems
 * / SRE-adjacent Operations / 99.9% Uptime ..." — and it scored *well*.
 *
 * So shape is a gate, not a score term: a candidate that is not prose is not a
 * candidate, however well it overlaps.
 */
export function looksLikeProse(text) {
  const words = String(text || '').trim().split(/\s+/).filter(Boolean);
  if (words.length < 20) return false;
  const slashes = (String(text).match(/\//g) || []).length;
  if (slashes >= 3) return false;                       // tag list, not a sentence
  if (!/[.!?]/.test(text)) return false;                // no sentence ever ends
  const fn = words.filter(w => FUNCTION_WORDS.has(w.toLowerCase().replace(/[^a-z]/g, ''))).length;
  return fn / words.length >= 0.12;
}

/**
 * CV filler: phrases that describe nobody. They survive every truth guard —
 * nothing about "a proven track record in diverse domains" is false — so only
 * an explicit penalty keeps them out.
 */
const FILLER = [
  'proven track record', 'high-impact', 'diverse domains', 'innovative solutions',
  'cutting-edge', 'passionate about', 'results-driven', 'team player',
  'thinking outside', 'wide range of', 'various domains', 'dynamic environment',
];

/** How many filler phrases a candidate leans on. */
export function fillerCount(text) {
  const t = String(text || '').toLowerCase();
  return FILLER.filter(f => t.includes(f)).length;
}

/**
 * Verbs a CV bullet opens with. A summary whose first sentence starts here is
 * describing an achievement, not the candidate — it is a bullet with the bullet
 * point removed.
 *
 * Same contract as NAMED_PRODUCTS: a *detector*, not a generator. A verb missing
 * from this list understates the defect rate, it never invents one. Seeded from
 * the openers actually observed across the shipped summaries in `output/`.
 */
const BULLET_VERBS = [
  'led', 'delivered', 'built', 'designed', 'developed', 'created', 'implemented',
  'migrated', 'raised', 'automated', 'owned', 'engineered', 'found', 'executed',
  'managed', 'conducted', 'architected', 'improved', 're-architected', 'ran',
  'authored', 'resolved', 'diagnosed', 'applied', 'identified', 'tracked', 'won',
];

/**
 * Shape defects in a summary, named. Empty array means the shape is sound.
 *
 * The eight generation metrics all measure *falsity*, and a summary can be
 * entirely true and still be unusable: three consecutive runs of offer 305
 * produced an achievement list, a 75-word single-sentence run-on, and an opener
 * reading "Experienced PM/Software Engineer with a proven track record". Every
 * falsity metric scored those identically. `summary_jd_fit` and `summary_cv_fit`
 * are cosines against the JD and the CV — the run-on scores *well* on both,
 * because it names every technology in the evidence.
 *
 * So this is the missing direction, in the same spirit as rule 9: the suite
 * could not see a summary that was true and shapeless. It is deliberately a
 * *shape* metric and nothing more — it cannot tell a well-chosen fact from a
 * badly-chosen one, and a two-word summary ("Backend engineer.") clears
 * `no_positioning` while failing `off_band`. Read it next to the falsity
 * metrics, never instead of them.
 *
 *   run_on         one sentence carrying the whole summary (>40 words). This is
 *                  also how `clampSummaryWords` gets defeated: it splits on
 *                  sentences and always keeps the first, so a single-sentence
 *                  75-word summary passes a hard 70-word band untouched.
 *   filler_open    the first sentence — the only one some readers finish —
 *                  leads on a phrase that describes nobody.
 *   no_positioning no sentence says what the candidate *is*; every one opens
 *                  with a bullet verb. This is the shipped 237 shape.
 *   off_band       outside the 50-70 words the stage claims to enforce.
 *
 * @param {string} summary
 * @returns {string[]}
 */
export function summaryShape(summary) {
  const s = String(summary || '').trim();
  if (!s) return ['empty'];
  const out = [];
  const sentences = s.split(/(?<=[.!?])\s+/).filter(Boolean);
  if (sentences.some(x => wordCount(x) > 40)) out.push('run_on');
  if (fillerCount(sentences[0]) > 0) out.push('filler_open');
  const opensAsBullet = (x) =>
    BULLET_VERBS.includes(String(x).trim().split(/\s+/)[0]?.toLowerCase().replace(/[^a-z-]/g, ''));
  if (sentences.every(opensAsBullet)) out.push('no_positioning');
  const w = wordCount(s);
  if (w < 50 || w > 70) out.push('off_band');
  return out;
}

/**
 * Deterministic quality score for one candidate summary. Higher is better.
 * Label-free: word-count distance, fabricated products, and how much of it is
 * traceable to the evidence. Non-prose scores -Infinity — see looksLikeProse.
 *
 * Shape is priced at 4 a defect, which is deliberately enough to cancel half the
 * evidence-overlap term: the 75-word run-on that shipped scored *well* on
 * overlap precisely because it named every technology in the evidence, and
 * nothing else in this function could see it. `off_band` is dropped because
 * `lenPenalty` already charges for length, at a rate that scales with how far
 * out it is.
 */
export function scoreSummary(text, { bullets, cvText }) {
  if (!text || !looksLikeProse(text)) return -Infinity;
  const w = wordCount(text);
  const lenPenalty = w < 50 ? 50 - w : w > 70 ? w - 70 : 0;
  const shape = summaryShape(text).filter(d => d !== 'off_band');
  return -lenPenalty
         - 5 * productFab(text, cvText).length
         - 4 * fillerCount(text)
         - 4 * shape.length
         + 8 * evidenceOverlap(text, bullets);
}

const wordCount = (s) => String(s || '').trim().split(/\s+/).filter(Boolean).length;

/**
 * Drop any sentence naming a proper noun that the posting contains and `cv.md`
 * does not.
 *
 * `productFab` is a closed allowlist of *technologies*, so it can only catch what
 * someone thought to list, and a company or product brand from the posting can
 * never be on it. Observed shipping: for a JD.com posting the summary claimed the
 * membership platform was built "for Joybuy Systems" — JD.com's own brand,
 * substituted for the real client. Every truth guard passed it. `productFab`
 * returned [], `metric_fab` reads only experience bullets, and the company-name
 * strip compares against the `--company` argument, which was "JD.com" and does
 * not match "Joybuy".
 *
 * The general rule is the one that actually holds: a name the posting supplies
 * and the CV does not is, by definition, not the candidate's. That needs no
 * vocabulary and cannot go stale.
 *
 * Sentence-initial words are skipped — every sentence starts with a capital, and
 * "Delivered" is not a proper noun.
 *
 * @param {string} summary
 * @param {string} cvText
 * @param {string} jdText
 */
export function stripJdProperNouns(summary, cvText, jdText) {
  const s = String(summary || '');
  if (!s || !jdText) return s;
  const norm = (t) => t.replace(/^[^A-Za-z0-9]+|[^A-Za-z0-9+#.]+$/g, '').replace(/^\.+|\.+$/g, '');
  const inText = (hay, word) => new RegExp(`\\b${word.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`, 'i').test(hay);

  const kept = s.split(/(?<=[.!?])\s+/).filter(sentence => {
    const words = sentence.split(/\s+/);
    for (let i = 0; i < words.length; i++) {
      const w = norm(words[i]);
      if (!w || w.length < 3) continue;
      if (i === 0 && !/^[A-Z]{2,}$/.test(w)) continue;
      if (!/^[A-Z]/.test(w)) continue;
      if (inText(cvText, w)) continue;
      if (inText(jdText, w)) return false;
    }
    return true;
  });
  // Never strip to nothing: an empty summary is a worse failure than a leaked
  // name, and the caller's length floor would pad it back into something
  // shapeless. Keeping the original lets the shipped guards downstream try.
  return kept.length ? kept.join(' ').trim() : s;
}

/**
 * Drop trailing sentences until the summary fits the band.
 *
 * `scoreSummary` penalises over-length but only ever *compares* — so an
 * over-long candidate that has no competitor ships at whatever length it came
 * out at. That is not hypothetical: with no incumbent the comparison is against
 * -Infinity and every challenger wins, and the observed output was a 130-word
 * run-on listing every bullet in turn. The band is a layout requirement (the PDF
 * is hard-capped at 2 pages), not a preference, so it is enforced rather than
 * scored.
 *
 * The first sentence is always kept: a summary trimmed to nothing is worse than
 * one trimmed to too-long, and the caller's <50-word pad can top it back up.
 *
 * That guarantee is also the hole. Keeping `sentences[0]` unconditionally means a
 * summary that *is* one sentence cannot be clamped at all, which is how a 75-word
 * run-on passed a hard 70-word band into a 2-page-capped PDF. The band is a
 * layout requirement rather than a preference, so the fallback cuts at the word
 * and closes the sentence. A mid-clause cut reads badly on purpose — it is the
 * backstop for a shape the prompt is supposed to prevent, not a repair.
 *
 * @param {string} text
 * @param {number} max
 */
export function clampSummaryWords(text, max = 70) {
  const s = String(text || '').trim();
  if (!s || wordCount(s) <= max) return s;
  const sentences = s.split(/(?<=[.!?])\s+/);
  let out = sentences[0];
  for (const next of sentences.slice(1)) {
    if (wordCount(`${out} ${next}`) > max) break;
    out += ` ${next}`;
  }
  if (wordCount(out) > max) {
    out = out.trim().split(/\s+/).slice(0, max).join(' ')
      .replace(/[.,;:!?]+$/, '') + '.';
  }
  return out.trim();
}

/** Strip the wrappers a model puts around a "plain text only" answer. */
export function cleanSummary(raw) {
  return String(raw || '')
    .trim()
    .replace(/^```[\s\S]*?\n|```$/g, '')
    .replace(/^["'`]+|["'`]+$/g, '')
    .replace(/^(summary|professional summary)\s*[:\-]\s*/i, '')
    .trim();
}

/**
 * Generate the summary from the selected evidence, and return it only if it
 * beats the candidate the main JSON call already produced.
 *
 * Best-of-N by resampling is pointless at the benchmark's temperature 0 — greedy
 * decoding is byte-identical, so N samples are one sample N times. Using the
 * JSON field as the second candidate gives a genuinely different draft for free
 * (it is already generated and paid for) and keeps the whole thing deterministic,
 * which is what makes a single-run A/B valid on this stack.
 *
 * @param {{bullets: string[], role: string, cvText: string, incumbent?: string,
 *          reqs?: string[],
 *          call: (system: string, user: string) => Promise<string>,
 *          margin?: number}} opts
 * @returns {Promise<string|null>} the winning summary, or null if neither works
 */
export async function generateSummary({ bullets, role, cvText, incumbent = '', reqs = [], call, margin = 1.0 }) {
  let challenger = null;
  try {
    const text = cleanSummary(await call(SUMMARY_SYSTEM, summaryUser(bullets, role, reqs)));
    if (text) challenger = stripFabricatedProducts(text, cvText);
  } catch { /* the incumbent still stands */ }

  const base = incumbent ? stripFabricatedProducts(incumbent, cvText) : null;
  const baseScore = base ? scoreSummary(base, { bullets, cvText }) : -Infinity;
  const chalScore = challenger ? scoreSummary(challenger, { bullets, cvText }) : -Infinity;

  // The incumbent is the shipped behaviour and holds the tie. A new stage only
  // displaces it by a clear margin, never on a rounding difference — measured
  // on offer 182, where the challenger was blander than the JSON field and a
  // bare `>` handed it the slot anyway.
  const winner = chalScore > baseScore + margin ? challenger : (base ?? challenger);
  // Enforced on the winner, not on each candidate: clamping before scoring would
  // hand a rambling candidate a free repair and let it beat a tight one on
  // evidence overlap it only had room for because it overran.
  return winner === null ? null : clampSummaryWords(winner);
}
