// @ts-check
/**
 * summary-stage.mjs — Phase 3 generation guards.
 *
 * Two jobs, both about making the generated prose true:
 *
 *   1. The summary is generated by its own call, fed the bullets that will
 *      actually appear on the CV. It used to be one field in a large JSON blob
 *      competing with five other sections, and its repair path
 *      (`reviseSummary`) was built from the JD and the profile narrative and
 *      **never saw the selected bullets at all** — structurally guaranteed to
 *      pull the summary toward the posting. That is the parroting failure mode,
 *      built into the repair.
 *
 *   2. A named product the CV never mentions is stripped, not counted. The
 *      two-tier vocabulary rule — capability phrases free, named products
 *      grounded — is aspirational until violations are actually rejected.
 */

import { parseCvSections, parseEntries, revertUnsupportedBullets } from './cv-select.mjs';

// ── Named-product vocabulary ──────────────────────────────────────────────────
/**
 * A closed vocabulary is deliberate. The alternative — treat any capitalised
 * unknown token as a product — flags every company name, role title and section
 * heading, and a guard that cries wolf gets switched off. This is a *detector*,
 * not a generator: a missing entry understates the count, it never invents one.
 *
 * Seeded from the 9 real violations found across 133 shipped CVs (gcp x3,
 * kotlin, golang, dbt, terraform, azure, angular) and extended to the products a
 * JD in this corpus is likely to name.
 */
export const NAMED_PRODUCTS = [
  // clouds & platforms
  'aws', 'azure', 'gcp', 'google cloud', 'heroku', 'digitalocean', 'cloudflare',
  'firebase', 'vercel', 'netlify', 'openshift', 'cloud foundry',
  // languages
  'kotlin', 'golang', 'scala', 'clojure', 'elixir', 'erlang', 'haskell', 'swift',
  'objective-c', 'perl', 'ruby', 'php', 'c#', 'f#', 'dart', 'julia', 'groovy',
  'visual basic', 'cobol', 'fortran', 'lua', 'r language',
  // frontend
  'angular', 'vue', 'svelte', 'ember', 'backbone', 'jquery', 'solidjs',
  'tailwind', 'bootstrap', 'material ui', 'sass', 'webpack', 'vite', 'nuxt',
  // backend & frameworks
  'django', 'flask', 'fastapi', 'rails', 'laravel', 'symfony', 'phoenix',
  'spring boot', 'quarkus', 'micronaut', 'nestjs', 'gin', 'echo framework',
  'asp.net', '.net core', 'entity framework',
  // data stores
  'cassandra', 'dynamodb', 'cockroachdb', 'couchbase', 'couchdb', 'neo4j',
  'influxdb', 'clickhouse', 'snowflake', 'bigquery', 'redshift', 'databricks',
  'oracle db', 'db2', 'mariadb', 'firestore', 'elasticsearch', 'opensearch',
  'timescaledb', 'scylladb', 'planetscale', 'supabase',
  // streaming & messaging
  'kafka', 'rabbitmq', 'pulsar', 'nats', 'activemq', 'sqs', 'kinesis',
  'flink', 'spark', 'hadoop', 'airflow', 'dagster', 'dbt', 'beam',
  // infra & ops
  'terraform', 'pulumi', 'ansible', 'puppet', 'chef', 'vagrant', 'nomad',
  'consul', 'vault', 'istio', 'linkerd', 'helm', 'argocd', 'flux',
  'cloudformation', 'packer', 'saltstack',
  // observability
  'datadog', 'new relic', 'splunk', 'sentry', 'grafana', 'jaeger', 'zipkin',
  'opentelemetry', 'pagerduty', 'dynatrace', 'appdynamics',
  // ci/cd & vcs
  'circleci', 'travis', 'teamcity', 'bamboo', 'gitlab ci', 'github actions',
  'bitbucket', 'azure devops', 'octopus deploy',
  // ml
  'pytorch', 'tensorflow', 'keras', 'jax', 'scikit-learn', 'huggingface',
  'langchain', 'llamaindex', 'mlflow', 'kubeflow', 'sagemaker', 'vertex ai',
  'weights & biases', 'ray',
  // saas / business
  'salesforce', 'sap', 'workday', 'servicenow', 'netsuite', 'hubspot',
  'shopify', 'magento', 'contentful', 'sanity', 'wordpress', 'drupal',
  'twilio', 'sendgrid', 'auth0', 'okta', 'keycloak', 'segment', 'snowplow',
  'looker', 'tableau', 'power bi', 'qlik', 'metabase', 'superset',
];

/** Normalised text with guaranteed leading/trailing space, for phrase matching. */
function phraseSpace(s) {
  return ` ${String(s || '').toLowerCase().replace(/[^a-z0-9+#.&-]+/g, ' ').replace(/\s+/g, ' ').trim()} `;
}
const hasPhrase = (haystack, phrase) => haystack.includes(` ${phrase} `);

/**
 * Named products the text claims that `cv.md` never mentions.
 * @param {string} text
 * @param {string} cvText
 * @returns {string[]}
 */
export function productFab(text, cvText) {
  const out = phraseSpace(text);
  const cv = phraseSpace(cvText);
  return NAMED_PRODUCTS.filter(p => hasPhrase(out, p) && !hasPhrase(cv, p));
}

/**
 * Drop the clauses that name a product `cv.md` never mentions.
 *
 * Sentence-level, then comma-clause-level: "Built services in Rust, Kotlin and
 * Go" should lose Kotlin, not the whole sentence. Falls back to deleting the
 * sentence only when the clause surgery cannot clear it, because shipping a
 * shorter true summary beats shipping a longer false one.
 *
 * @param {string} text
 * @param {string} cvText
 * @returns {string}
 */
export function stripFabricatedProducts(text, cvText) {
  if (!text) return text;
  if (!productFab(text, cvText).length) return text;

  const sentences = String(text).split(/(?<=[.!?])\s+/);
  const kept = [];
  for (const sentence of sentences) {
    if (!productFab(sentence, cvText).length) { kept.push(sentence); continue; }
    // Try clause surgery before giving up on the whole sentence.
    const clauses = sentence.split(/,\s*/);
    const clean = clauses.filter(c => !productFab(c, cvText).length);
    if (clean.length && clean.length < clauses.length) {
      const rebuilt = clean.join(', ').replace(/\s+and\s*$/i, '').replace(/,\s*$/, '').trim();
      // Only keep the repair if it actually cleared the fabrication — a product
      // sitting in the sentence's only clause survives the join otherwise.
      if (rebuilt && !productFab(rebuilt, cvText).length) {
        kept.push(/[.!?]$/.test(rebuilt) ? rebuilt : `${rebuilt}.`);
      }
    }
  }
  return kept.join(' ').replace(/\s+/g, ' ').trim();
}

/**
 * Revert every experience bullet naming a product `cv.md` never mentions.
 *
 * Bullets get reverted rather than clause-stripped because each one has a known
 * source line in `cv.md` — the untailored truth is right there, and it fills the
 * slot. Summaries and project blurbs have no single source line, so those get
 * `stripFabricatedProducts` instead.
 *
 * @param {any[]} items
 * @param {string} cvText
 */
export function verifyBulletProducts(items, cvText) {
  return revertUnsupportedBullets(items, cvText, b => productFab(b, cvText).length > 0);
}

// ── Summary stage ─────────────────────────────────────────────────────────────

/**
 * The bullets that will actually appear on this CV, in CV order.
 * This is the evidence the summary must describe — not the JD, and not the
 * whole of `cv.md`, but the specific subset `cv-select` chose for this offer.
 * @param {string} selectedCv the post-selection CV handed to the tailor model
 * @returns {string[]}
 */
export function selectedBullets(selectedCv) {
  const out = [];
  try {
    for (const sec of parseCvSections(selectedCv)) {
      if (sec.name !== 'Experience' && sec.name !== 'Projects') continue;
      for (const e of parseEntries(sec.lines).entries) {
        const name = e.head[0].replace(/^###\s+/, '').trim();
        for (const b of e.bullets) out.push(`${name}: ${b}`);
      }
    }
  } catch { /* odd CV shape — caller falls back */ }
  return out;
}

const SUMMARY_SYSTEM = [
  'You write ONE professional summary for a CV. Output ONLY the summary as plain text —',
  'no JSON, no quotes, no preamble, no label.',
  '',
  'Rules:',
  '- Length: 50 to 70 words. Count them. This is mandatory.',
  '- Implied first person: never use a name, never "he"/"she"/"they".',
  '- EVERY claim must be supported by the evidence below. The evidence is the only',
  '  source of fact. If the role asks for something the evidence does not show, do',
  '  not claim it — say nothing about it.',
  '- Never name the target company, and never claim to have worked for them.',
  '- Never name a technology, product, cloud or framework that does not appear in',
  '  the evidence. Describing the *kind* of work ("distributed systems",',
  '  "low-latency") is fine; naming a product you cannot see is not.',
  '- Lead with what the evidence shows. Use the role context only to decide which',
  '  parts of the evidence to foreground, never as material to copy.',
].join('\n');

/**
 * @param {string[]} bullets  the selected CV bullets — the ONLY source of fact
 * @param {string[]} reqs     Block B requirements, for emphasis only
 * @param {string} role
 */
export function summaryUser(bullets, reqs, role) {
  const ev = bullets.length ? bullets.map(b => `- ${b}`).join('\n') : '(none)';
  const rq = (reqs || []).length ? reqs.slice(0, 10).map(r => `- ${r}`).join('\n') : '(unspecified)';
  return [
    '## Evidence — the bullets that will appear on this CV',
    '',
    ev,
    '',
    `## The role being targeted: ${role || 'software engineering'}`,
    '',
    'It asks for:',
    '',
    rq,
    '',
    'Write the 50-70 word summary now, grounded entirely in the evidence.',
  ].join('\n');
}

const wordCount = (s) => String(s || '').trim().split(/\s+/).filter(Boolean).length;

/** Strip the wrappers a model puts around a "plain text only" answer. */
export function cleanSummary(raw) {
  return String(raw || '')
    .trim()
    .replace(/^```[\s\S]*?\n|```$/g, '')
    .replace(/^["'`]+|["'`]+$/g, '')
    .replace(/^(summary|professional summary)\s*[:\-]\s*/i, '')
    .trim();
}

/**
 * Generate the summary from the selected evidence.
 *
 * Samples up to `attempts` times and keeps the best by a code-side score, which
 * turns a generation problem into a selection problem — selection is code, and
 * therefore reliable. Scoring is deterministic and label-free: land the word
 * count, name no fabricated product, and stay close to the evidence.
 *
 * @param {{bullets: string[], reqs: string[], role: string, cvText: string,
 *          call: (system: string, user: string) => Promise<string>,
 *          attempts?: number}} opts
 * @returns {Promise<string|null>}
 */
export async function generateSummary({ bullets, reqs, role, cvText, call, attempts = 2 }) {
  const user = summaryUser(bullets, reqs, role);
  let best = null, bestScore = -Infinity;
  for (let i = 0; i < attempts; i++) {
    let text;
    try { text = cleanSummary(await call(SUMMARY_SYSTEM, user)); } catch { continue; }
    if (!text) continue;
    const stripped = stripFabricatedProducts(text, cvText);
    const w = wordCount(stripped);
    // Distance outside the 50-70 band dominates; a fabrication that had to be
    // stripped is a real penalty even though the strip already fixed it, because
    // a model that reached for one will have shaded the rest too.
    const score = -Math.abs(w < 50 ? 50 - w : w > 70 ? w - 70 : 0)
                  - 5 * productFab(text, cvText).length;
    if (score > bestScore) { best = stripped; bestScore = score; }
    if (bestScore === 0) break;  // in range and clean — no reason to sample again
  }
  return best;
}
